apiVersion: v1
kind: Service
metadata:
  name: pull-request-service
spec:
  selector:
    app: pull-request-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer